# Generated by Django 2.2.7 on 2019-11-06 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField()),
                ('short_url', models.TextField()),
                ('reg_date', models.DateTimeField(auto_now=True)),
                ('life_span', models.IntegerField(validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
